### ISSUE TITLE
crc compute wrong when set ref_in to True

### ISSUE THREAD

**Issue by tooyangtoonaive** [GardenTools/CrcEngine#325]
**Describe the bug**
crc compute wrong when set ref_in to True

**To Reproduce**

```
import crcengine
import sys
import math

data = 0X20

input = data.to_bytes(math.ceil((hex(data).__len__() - 2) / 2), "big")

my_crc_algorithm = crcengine.create(poly=0x07,
								 width=8,
								 seed=0X55,
								 ref_in=1,
								 ref_out=0,
								 name="test",
								 xor_out=0x0)

result = my_crc_algorithm(input)
print(str(input.__len__()) + " " + hex(result))
```

output: 0x43
Expected output:  0xb0

website [http://www.zorc.breitbandkatze.de/crc.html](http://www.zorc.breitbandkatze.de/crc.html) show a correct result:
![image](https://user-images.githubusercontent.com/19810827/175475237-b8686719-5f97-4b5c-bf2e-4f21c060ecf3.png)

**Desktop (please complete the following information):**
 - OS: win10
 - python 3.8.10

**Comment by GardenTools** [comment]
Hi @tooyangtoonaive , thanks for the report, I will see if I can figure out what is going on there. In the meantime, using create_generic() gives the answer that you expect (but is a slower algorithm).

Continuing from your example:

```
    eng_gen = crcengine.create_generic(poly=0x07,
                                       width=8,
                                       seed=0X55,
                                       ref_in=1,
                                       ref_out=0,
                                       name="test_gen",
                                       xor_out=0x0)
    result2 = eng_gen.calculate(input)
    print(str(input.__len__()) + " " + hex(result2))
```

Produces `1 0xb0` for your data
